# Classe contenant les constantes
class Constant :

    PARAM_CHEMIN_FICHIER = "-f";
    PARAM_INTERACTION_UTILISATEUR = "-u";
    PARAM_LOG = "-l";
    TYPE_QUALITATIVE_OBJECT = "object";
    TYPE_QUANTITATIVE_INT = "int64";
    TYPE_QUANTITATIVE_FLOAT = "float64";
    PARAM_INFO_FICHIER = "f";
    PARAM_INFO_DONNEES = "d";
    PARAM_QUITTER = "q";
    PARAM_TAILLE_FICHIER ="t";
    PARAM_ENCODAGE_FICHIER = "e";
    PARAM_DERNIERE_MODIF_FICHIER = "d";
    PARAM_TOUT_INFOS_FICHIER = "a";
    PARAM_RETOUR = "r";
    PARAM_INFOS_TABLE = "b";
    PARAM_INFOS_QUANTITATIVE = "v";
    PARAM_INFOS_QUALITATIVE = "l";
    PARAM_PLOT = "p";
